"""Aggregates ClusteringStore tables into a `corpus` dict that mine_candidates consumes."""
from __future__ import annotations
from collections import defaultdict
from typing import Any

from core.playbooks.miner import mine_candidates
from core.playbooks.store import PlaybookStore


def build_corpus(clustering_store) -> tuple[dict, dict[str, int]]:
    """Returns (corpus, domain_totals). Domain totals = {domain_label: count_agreements}."""
    conn = clustering_store.conn

    # Per-domain agreement count
    rows = conn.execute(
        "SELECT d.label, COUNT(*) "
        "FROM agreements a JOIN domains d ON a.domain_id = d.domain_id "
        "GROUP BY d.label"
    ).fetchall()
    domain_totals = {label: int(n) for label, n in rows if label}

    # Per-(domain, cluster) clause count via clauses → agreements → domains → clusters.
    # Fall back to per-domain × clusters if cluster_assignments table has no data.
    rows = conn.execute(
        "SELECT d.label AS domain_label, c.label AS cluster_label, COUNT(DISTINCT a.agreement_id) "
        "FROM clauses cl "
        "JOIN agreements a ON cl.agreement_id = a.agreement_id "
        "JOIN domains d ON a.domain_id = d.domain_id "
        "JOIN clusters c ON cl.clause_type_id = c.cluster_id "
        "GROUP BY d.label, c.label"
    ).fetchall()
    domain_clusters: dict[str, dict[str, int]] = defaultdict(dict)
    for d_label, c_label, n in rows:
        if d_label and c_label:
            domain_clusters[d_label][c_label] = int(n)

    # Per-(domain, cluster, field) value lists
    rows = conn.execute(
        "SELECT d.label AS domain_label, c.label AS cluster_label, "
        "       f.name AS field_name, e.value "
        "FROM extractions e "
        "JOIN field_definitions f ON e.field_id = f.field_id "
        "JOIN clusters c ON f.cluster_id = c.cluster_id "
        "JOIN agreements a ON e.agreement_id = a.agreement_id "
        "JOIN domains d ON a.domain_id = d.domain_id"
    ).fetchall()
    field_values: dict[str, list] = defaultdict(list)
    for d_label, c_label, fname, value in rows:
        if not (d_label and c_label and fname):
            continue
        key = f"{d_label}::{c_label}::{fname}"
        # Coerce numeric strings to floats; leave others as strings; keep None as None
        if value is None:
            field_values[key].append(None)
        else:
            try:
                field_values[key].append(float(value))
            except (TypeError, ValueError):
                field_values[key].append(str(value))

    corpus: dict[str, Any] = {
        "domain_clusters": dict(domain_clusters),
        "field_values": dict(field_values),
    }
    return corpus, domain_totals


def run_miner(clustering_store, playbook_store: PlaybookStore, *,
              playbook_name: str = "Auto-mined draft",
              owner_org: str = "auto") -> tuple[str, list[dict]]:
    """End-to-end: build corpus → create draft playbook → mine candidates.
    Returns (playbook_id, candidates)."""
    corpus, domain_totals = build_corpus(clustering_store)
    pid = playbook_store.create_playbook(name=playbook_name, owner_org=owner_org,
                                          description="Generated by miner_runner")
    n_total = max(domain_totals.values()) if domain_totals else 1
    cands = mine_candidates(playbook_store, pid, corpus, n_total_per_domain=n_total)
    return pid, cands
